name:                ComposingTypes
version:             0.1.0.0

dependencies:
- base >= 4.7 && < 5
- hspec

library:
  source-dirs: src

tests:
  ComposingTypes-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - ComposingTypes
